FROM php:8.2-fpm

ARG user
ARG uid

RUN apt update && apt install -y curl \
                   libpng-dev \
                   libonig-dev \
                   libxml2-dev \
                   libpq-dev \
                   zip \
                   unzip \
                   librdkafka-dev

RUN docker-php-ext-install pdo pdo_pgsql pgsql mbstring exif pcntl bcmath gd \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql

RUN pecl install rdkafka \
    && docker-php-ext-enable rdkafka

COPY --from=composer /usr/bin/composer /usr/bin/composer

RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

WORKDIR /var/www

USER $user

EXPOSE 9000
